//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.03 at 08:10:08 PM PST 
//


package com.microsoft.hsg.methods.jaxb.authmethod;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.authMethod" xmlns:wc-types="urn:com.microsoft.wc.types"/&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;remarks xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.authMethod" xmlns:wc-types="urn:com.microsoft.wc.types"/&gt;
 * </pre>
 * 
 * 
 * <p>Java class for MethodGroupsXml complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MethodGroupsXml">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="method-groups" type="{urn:com.microsoft.wc.authMethod}MethodGroups"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MethodGroupsXml", propOrder = {
    "methodGroups"
})
public class MethodGroupsXml {

    @XmlElement(name = "method-groups", required = true)
    protected MethodGroups methodGroups;

    /**
     * Gets the value of the methodGroups property.
     * 
     * @return
     *     possible object is
     *     {@link MethodGroups }
     *     
     */
    public MethodGroups getMethodGroups() {
        return methodGroups;
    }

    /**
     * Sets the value of the methodGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodGroups }
     *     
     */
    public void setMethodGroups(MethodGroups value) {
        this.methodGroups = value;
    }

}
