//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.03 at 08:10:08 PM PST 
//


package com.microsoft.hsg.methods.jaxb.authmethod;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MethodNames.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MethodNames">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Account"/>
 *     &lt;enumeration value="RecordData"/>
 *     &lt;enumeration value="RecordInfo"/>
 *     &lt;enumeration value="Application"/>
 *     &lt;enumeration value="OpenQuery"/>
 *     &lt;enumeration value="Messaging"/>
 *     &lt;enumeration value="SystemAdmin"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MethodNames")
@XmlEnum
public enum MethodNames {


    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.authMethod" xmlns:wc-types="urn:com.microsoft.wc.types"/&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("Account")
    ACCOUNT("Account"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.authMethod" xmlns:wc-types="urn:com.microsoft.wc.types"/&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("RecordData")
    RECORD_DATA("RecordData"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.authMethod" xmlns:wc-types="urn:com.microsoft.wc.types"/&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("RecordInfo")
    RECORD_INFO("RecordInfo"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.authMethod" xmlns:wc-types="urn:com.microsoft.wc.types"/&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("Application")
    APPLICATION("Application"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.authMethod" xmlns:wc-types="urn:com.microsoft.wc.types"/&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("OpenQuery")
    OPEN_QUERY("OpenQuery"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.authMethod" xmlns:wc-types="urn:com.microsoft.wc.types"/&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("Messaging")
    MESSAGING("Messaging"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.authMethod" xmlns:wc-types="urn:com.microsoft.wc.types"/&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("SystemAdmin")
    SYSTEM_ADMIN("SystemAdmin");
    private final String value;

    MethodNames(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MethodNames fromValue(String v) {
        for (MethodNames c: MethodNames.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
