//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.07 at 01:43:24 AM PST 
//


package com.microsoft.hsg.thing.oxm.jaxb.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.types"&gt;
 *                     Represents a specific culture by combining a language and
 *                     country/region.
 *                 &lt;/summary&gt;
 * </pre>
 * 
 * 
 * <p>Java class for Culture complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Culture">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="language" type="{urn:com.microsoft.wc.types}iso639-1" minOccurs="0"/>
 *         &lt;element name="country" type="{urn:com.microsoft.wc.types}iso3166" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Culture", propOrder = {
    "language",
    "country"
})
public class Culture {

    protected Iso6391 language;
    protected Iso3166 country;

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link Iso6391 }
     *     
     */
    public Iso6391 getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link Iso6391 }
     *     
     */
    public void setLanguage(Iso6391 value) {
        this.language = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link Iso3166 }
     *     
     */
    public Iso3166 getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link Iso3166 }
     *     
     */
    public void setCountry(Iso3166 value) {
        this.country = value;
    }

}
