//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.03 at 08:22:44 PM PST 
//


package com.microsoft.hsg.methods.jaxb.application;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.microsoft.hsg.methods.jaxb.application package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.microsoft.hsg.methods.jaxb.application
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AppSmallLogoInfo }
     * 
     */
    public AppSmallLogoInfo createAppSmallLogoInfo() {
        return new AppSmallLogoInfo();
    }

    /**
     * Create an instance of {@link App }
     * 
     */
    public App createApp() {
        return new App();
    }

    /**
     * Create an instance of {@link StatementInfo }
     * 
     */
    public StatementInfo createStatementInfo() {
        return new StatementInfo();
    }

    /**
     * Create an instance of {@link AppIdAndIncrAuth }
     * 
     */
    public AppIdAndIncrAuth createAppIdAndIncrAuth() {
        return new AppIdAndIncrAuth();
    }

    /**
     * Create an instance of {@link CultureSpecificAppSmallLogo }
     * 
     */
    public CultureSpecificAppSmallLogo createCultureSpecificAppSmallLogo() {
        return new CultureSpecificAppSmallLogo();
    }

    /**
     * Create an instance of {@link PublicKeys }
     * 
     */
    public PublicKeys createPublicKeys() {
        return new PublicKeys();
    }

    /**
     * Create an instance of {@link SodaAppConfig }
     * 
     */
    public SodaAppConfig createSodaAppConfig() {
        return new SodaAppConfig();
    }

    /**
     * Create an instance of {@link CultureSpecificStatement }
     * 
     */
    public CultureSpecificStatement createCultureSpecificStatement() {
        return new CultureSpecificStatement();
    }

    /**
     * Create an instance of {@link AppPersistentTokens }
     * 
     */
    public AppPersistentTokens createAppPersistentTokens() {
        return new AppPersistentTokens();
    }

    /**
     * Create an instance of {@link CultureSpecificAppLargeLogo }
     * 
     */
    public CultureSpecificAppLargeLogo createCultureSpecificAppLargeLogo() {
        return new CultureSpecificAppLargeLogo();
    }

    /**
     * Create an instance of {@link AppWithLogos }
     * 
     */
    public AppWithLogos createAppWithLogos() {
        return new AppWithLogos();
    }

    /**
     * Create an instance of {@link ApplicationAttributes }
     * 
     */
    public ApplicationAttributes createApplicationAttributes() {
        return new ApplicationAttributes();
    }

    /**
     * Create an instance of {@link AppLargeLogoInfo }
     * 
     */
    public AppLargeLogoInfo createAppLargeLogoInfo() {
        return new AppLargeLogoInfo();
    }

}
